Console.WriteLine("Eu não sei de onde vem");
Console.WriteLine("Essa força que me leva pra você");
Console.WriteLine("(Eu só sei que faz bem)");
Console.WriteLine("(Mas confesso que no fundo eu duvidei)");
Console.WriteLine("Tive medo e em segredo");
Console.WriteLine("Guardei o sentimento e me sufoquei");
Console.WriteLine("Mas agora é a hora");
Console.WriteLine("Vou gritar pra todo mundo (joga a mão e grita)");
Console.WriteLine("Eu tô apaixonado (eu tô contando tudo)");
Console.WriteLine("(E não tô nem ligando pro que vão dizer)");
Console.WriteLine("(Amar não é pecado e se eu tiver errado)");
